# Generated by Django 3.2.4 on 2025-04-22 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chargers_cables', 'Chargers & Cables'), ('audio_accessories', 'Audio Accessories'), ('phone_cases', 'Phone Cases & Covers'), ('screen_protection', 'Screen Protection'), ('car_accessories', 'Car Accessories'), ('smart_gadgets', 'Smart Gadgets'), ('camera_lenses', 'Camera Lenses & Enhancers'), ('cleaning_maintenance', 'Cleaning & Maintenance'), ('power_banks', 'Power Banks & Batteries'), ('adapters_converters', 'Adapters & Converters')], default='smart_gadgets', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
